name: Build APK

on:
  workflow_dispatch:
  push:
    paths:
      - "mobile/**"
      - ".github/workflows/build-apk.yml"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.4"

      - name: Flutter Pub Get
        working-directory: mobile
        run: flutter pub get

      - name: Build APK (release)
        working-directory: mobile
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: mobile/build/app/outputs/flutter-apk/app-release.apk
