name: Build APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.4"

      - name: Select working directory (root or mobile/)
        id: where
        shell: pwsh
        run: |
          if (Test-Path "mobile/pubspec.yaml") { echo "workdir=mobile" >> $env:GITHUB_OUTPUT }
          elseif (Test-Path "pubspec.yaml") { echo "workdir=." >> $env:GITHUB_OUTPUT }
          else { throw "pubspec.yaml not found" }

      # NEW: generate missing Android project files
      - name: Create Android platform
        shell: pwsh
        run: flutter create . --platforms=android
        working-directory: ${{ steps.where.outputs.workdir }}

      - name: Flutter pub get
        shell: pwsh
        run: flutter pub get
        working-directory: ${{ steps.where.outputs.workdir }}

      - name: Build release APK
        shell: pwsh
        run: flutter build apk --release
        working-directory: ${{ steps.where.outputs.workdir }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ steps.where.outputs.workdir }}/build/app/outputs/flutter-apk/app-release.apk
